# This file is auto-generated by ShipLens release CI.
# Do not edit by hand — see .github/workflows/release.yml in
# https://github.com/Ender-Wang/ShipLens.
class Shiplens < Formula
  desc "First release version of every line of code, inline in your terminal"
  homepage "https://github.com/Ender-Wang/ShipLens"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Ender-Wang/ShipLens/releases/download/v0.1.2/shiplens-cli-v0.1.2-darwin-arm64.tar.gz"
      sha256 "dd13b0623b6929e67d39cf1fab1c53edd2dd3891d3d5751d4b9894bf3e5c6983"
    else
      url "https://github.com/Ender-Wang/ShipLens/releases/download/v0.1.2/shiplens-cli-v0.1.2-darwin-amd64.tar.gz"
      sha256 "43742e8de2bcf86649ab1b36578caa1a7f1c90942c125b5979ba4e6ef574d273"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Ender-Wang/ShipLens/releases/download/v0.1.2/shiplens-cli-v0.1.2-linux-arm64.tar.gz"
      sha256 "4fdd902e7866b7d8a320c49cf9fbaffc5fa5ddcff12c630d9cdbc7c791d39c2f"
    else
      url "https://github.com/Ender-Wang/ShipLens/releases/download/v0.1.2/shiplens-cli-v0.1.2-linux-amd64.tar.gz"
      sha256 "e11d61b621de2f1e1b8a61d85c2d29fcce19a5d08ac5d97b568955aa74b7250c"
    end
  end

  def install
    bin.install "shiplens"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/shiplens version")
  end
end
