# This file is auto-generated by ShipLens release CI.
# Do not edit by hand — see .github/workflows/release.yml in
# https://github.com/Ender-Wang/ShipLens.
class Shiplens < Formula
  desc "First release version of every line of code, inline in your terminal"
  homepage "https://github.com/Ender-Wang/ShipLens"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Ender-Wang/ShipLens/releases/download/v0.1.3/shiplens-cli-v0.1.3-darwin-arm64.tar.gz"
      sha256 "64e2273d3b5df1bc0c96dedc714987afa1db7eea00ef3cb6941b1f9543078490"
    else
      url "https://github.com/Ender-Wang/ShipLens/releases/download/v0.1.3/shiplens-cli-v0.1.3-darwin-amd64.tar.gz"
      sha256 "d1121efa78947e529dab06326f62ab5805065960cbdf53b13c7570cc5595201c"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Ender-Wang/ShipLens/releases/download/v0.1.3/shiplens-cli-v0.1.3-linux-arm64.tar.gz"
      sha256 "63cd8389004ea72be2ad1488fcb611b26be9601837b7e8921968e43c839ac82e"
    else
      url "https://github.com/Ender-Wang/ShipLens/releases/download/v0.1.3/shiplens-cli-v0.1.3-linux-amd64.tar.gz"
      sha256 "4c8f07bbe1d7435b95b61535d81e908c0b40c4a5ccb35dc12efc001e992a0b28"
    end
  end

  def install
    bin.install "shiplens"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/shiplens version")
  end
end
