# This file is auto-generated by ShipLens release CI.
# Do not edit by hand — see .github/workflows/release.yml in
# https://github.com/Ender-Wang/ShipLens.
class Shiplens < Formula
  desc "First release version of every line of code, inline in your terminal"
  homepage "https://github.com/Ender-Wang/ShipLens"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Ender-Wang/ShipLens/releases/download/v0.1.3/shiplens-cli-v0.1.3-darwin-arm64.tar.gz"
      sha256 "b4961b4909954596beb8e7a81c654fe6206b64ed5de90ebe1e7cadc7a74e15a7"
    else
      url "https://github.com/Ender-Wang/ShipLens/releases/download/v0.1.3/shiplens-cli-v0.1.3-darwin-amd64.tar.gz"
      sha256 "bf7225683371cb41e384bcbcd7a3e018b506fb3f4b74e29648d38393793df573"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Ender-Wang/ShipLens/releases/download/v0.1.3/shiplens-cli-v0.1.3-linux-arm64.tar.gz"
      sha256 "2204c321ee62fb67e5566d53c4719c73b6aa8b66f65bd947e1b335cad0cf552d"
    else
      url "https://github.com/Ender-Wang/ShipLens/releases/download/v0.1.3/shiplens-cli-v0.1.3-linux-amd64.tar.gz"
      sha256 "d409e240f12214e2fe80a26636a846f65490bad52b5752e4b0507dd8a5594157"
    end
  end

  def install
    bin.install "shiplens"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/shiplens version")
  end
end
